# Citizens Configuration

general:
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
    message-error: <c>
  translation:
    locale: ''
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
  debug-file: ''
npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  default:
    look-close:
      enabled: false
      range: 5
      random-look-enabled: false
      random-look-delay: 60
      disable-while-navigating: true
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
    waypoints:
      cache-paths: false
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
    remove-packet-delay: 1
  chunks:
    always-keep-loaded: true
  skins:
    max-retries: -1
    use-latest: true
    view-distance: 100.0
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
  pathfinding:
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
    default-distance-margin: 2
    update-path-rate: 20
    maximum-new-pathfinder-iterations: 50000
    default-path-distance-margin: 1
    disable-mc-fallback-navigation: true
    new-finder:
      iterations-per-tick: 25000
      check-bounding-boxes: false
      open-doors: false
    minecraft:
      max-fall-distance: 3
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '340'
  controllable:
    use-boat-controls: true
    max-ground-speed: 0.5
    ground-direction-modifier: 1.0
  teleport-delay: -1
  player-scoreboard-teams:
    enable: true
  always-use-name-holograms: false
  hologram:
    default-line-height: 0.4
  commands:
    error-messages:
      maximum-times-used: You have reached the maximum number of uses ({0}).
      no-permission: You don't have permission to do that.
      not-enough-money: You need at least ${0}.
      on-cooldown: Please wait {0} more seconds.
advanced:
  check-minecraft-version: true
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins
