# DO NOT TOUCH
config-version: 4

# Edit general plugin number formatting here.
number-format:
  decimal-separator: .

# This is the formula for how defense works. It does
# NOT apply operators precedence. Placeholders:
# #damage# - Damage Dealt
# #defense# - Player Defense
defense-application: '#damage# * (1 - (#defense# / (#defense# + 100)))'

# Allows to scale health up/down to a specific
# amount so extra health does not fill up the screen.
# Requires a SERVER reload when changed.
# Delay should be used if your Users experience issues revolving around seeing too many hearts still. This can occur with plugins such as MySQL Inventory Bridge
# The delay is in ticks. 20 ticks = 1 second
health-scale:
  enabled: true
  scale: 20
  delay: 20

# Set to false to prevent players from dealing damage to other
# players using abilities. This is an useful option for PvE servers.
player-ability-damage: true

critical-strikes:
  weapon:
    # Default = 2 meaning crits deal 200% of the initial damage
    coefficient: 2
    cooldown: 3
    max-chance: 80
  skill:
    # Default = 1.5 meaning crits deal 150% of the initial damage
    coefficient: 1.5
    cooldown: 3
    max-chance: 80

# Default and max. values of armor stats. These systems
# all have a cooldown which can be reduced using the
# '*** Cooldown Reduction' item stat.
mitigation:

  # Edit mitigation messages here. Leave to blank for no message.
  message:

    # Whether or not they should display on action bar instead of chat
    action-bar: false

    parry: '&cYou just parried #damage# damage.'
    block: '&cYou just blocked #damage# damage.' # Use #power# to display block power.
    dodge: '&cYou just dodged #damage# damage.'

  block:
    power:
      default: 25.0
      max: 75.0
    rating-max: 80.0
    cooldown:
      base: 5.0
      min: 10.0

  dodge:
    knockback:
      enabled: true
      force: 1.0
    rating-max: 80.0
    cooldown:
      base: 5.0
      min: 1.0

  parry:
    knockback:
      enabled: true
      force: 1.0
    rating-max: 80.0
    cooldown:
      base: 8.0
      min: 2.0

# Displays in-game damage or heal indicators.
# Requires /reload when changed.
# Supported Plugins:
# - CMI
# - HolographicDisplays
# - Holograms
# - TrHologram
game-indicators:
  damage:
    enabled: true
    decimal-format: '0.#'
    format: '&c&lâœœ -#'
  regen:
    enabled: false
    decimal-format: '0.#'
    format: '&a+#'