#------------------------------------------------------------------------------------------------------#
#            _____                 _       _ _             _    _____           _                      #
#           / ____|               (_)     | (_)           | |  / ____|         | |                     #
#          | (___  _ __   ___  ___ _  __ _| |_ _______  __| | | |     _ __ __ _| |_ ___  ___           #
#           \___ \| '_ \ / _ \/ __| |/ _` | | |_  / _ \/ _` | | |    | '__/ _` | __/ _ \/ __|          #
#           ____) | |_) |  __/ (__| | (_| | | |/ /  __/ (_| | | |____| | | (_| | ||  __/\__ \          #
#          |_____/| .__/ \___|\___|_|\__,_|_|_/___\___|\__,_|  \_____|_|  \__,_|\__\___||___/          #
#                 | |                                                                                  #
#                 |_|                                                                                  #
#------------------------------------------------------------------------------------------------------#


#---------------------------------------#
#           Mechanic Settings           #
#---------------------------------------#

# How would you to store player statistics? Current options: FLATFILE, PLAYERFILES
# FLATFILE: Every player's data is stored in one single file.
# PLAYERFILES: Every player has their own file that stores their data.
# MYSQL: Use a database to store information. Use the MySQL.yml file to setup database info.
store-data: FLATFILE

# What plugin status messages would you like to be logged into console?
# Options:
#  EVERYTHING - Logs successful loads and failed loads.
#  FAILURES - Logs all loading failures.
#  NOTHING - Logs nothing at all to console.
log-successes: FAILURES

# When should player data be saved when using the FLATFILE data handler?
#   Options: DISABLE, INTERVAL
#   DISABLE: Player data is saved when the plugin is disabled (server stopped, reload, restart). This
#     is the MOST efficient and least resource consuming but will result in data loss on crashes.
#   INTERVAL: Player data is saved on an interval specified by 'data-save-interval' and ALSO when
#     the plugin is disabled (server stopped, reload, restart). The player data is only saved on the
#     interval if there has been a change. If nothing has been written to the file, it is not saved.
#     This is the LEAST efficient method as a file is periodically saved to disk but is safest and is
#     unlikely to lose data on crashes
flatfile-save-method: INTERVAL

# What should the interval, in SECONDS, be to save the player data?
#   Note: If there is no new player data to save, it won't save - the interval is to check IF
#   there is new information to be saved, and, if so, to save it.
flatfile-save-interval: 300

# What amount of history be kept for the player?
#
# Set to -1 to keep all player history and anything above that to keep that amount of most recent
#   history data for a player. (i.e. if it was set to 20, the last 20 crates worth of data for a
#   player would be kept - anything beyond that would be purged).
#
# Why purge old crate history data? The more data the player has to their name, the longer it takes
#   to load their history, the more server resources that are consumed every time a player joins.
player-history-limit: 500

# Is the plugin in debug mode?
debug: false

#------------------------------------#
#            Key Settings            #
#------------------------------------#

# Should the lore for a key be required to match the crate's key to work?
require-key-lore: true

# Should shift clicking allow the user to open a crate with every key the
#   player is holding?
#  NOTE: Skipping the animation by using every key at once only gives 1 rewards per
#    key, regardless of the animation type.
shift-click-open-all: true

# Should the player have to shift click the crate again to confirm opening
#   it with every key / virtual key?
shift-click-confirm: true

# When a player's inventory is full and they're given a key, should they get
#   a virtual key (true) instead of dropping it on the floor (false)?
virtual-key-instead-of-drop: false

# When a player left clicks with a key, it won't be cancelled - this is mainly to
#   support compatibility with sell-shop plugins that need the key to be interactable.
key-allow-left-click-interaction: false

# When a player left clicks with a key in hand, it opens up the reward preview menu
#   for that specific crate.
left-click-key-preview: false

#------------------------------------#
#           Crate Settings           #
#------------------------------------#

# How many open inventory slots are required to open a crate?
required-slots: 1

# Do you want explosions to destroy dynamic crates?
explosions-destroy-dynamic-crates: true

# Should the player be pushed back when the wrong key is used?
push-back: true

# Should people be allowed to place crates in creative mode?
place-creative: true

# Should people be allowed to open crates in creative mode?
open-creative: true

# How many blocks should the hologram be offset from its original place?
#    Note: This value applies to ALL crates, each individual crate can have its
#          own hologram-offset set in their respective files.
hologram-offset: 0

# Should the break effect be played when a crate is placed / created?
place-effect: true

# Should the player have to confirm to open the crate or not?
confirm-open: false

# How long should the crate-opening confirmation take to cancel, in seconds?
#   NOTE: Also works for the shift-click confirmation.
confirm-timeout: 3

# Every time the server or plugin is reloaded/restarted, should the crates always
#   be replaced to make sure that they haven't been overridden by worldedit, etc.?
keep-crate-block-consistent: true

# How many blocks away should players be able to see particles?
particle-view-distance: 25

# Should any %crate% placeholders use the crate item's display name instead of
#  of the crate name?
use-crate-name-for-display: true

#-------------------------------------------#
#           Crate Action Settings           #
#-------------------------------------------#

# Referring to the Action Bar, Title, and/or Subtitle...

# How long would you like the message to take, in seconds, to fade in?
fade-in-time: 0

# How long would you like the message to stay on the screen, in seconds?
stay-time: 4

# How long would you like the message to take, in seconds, to fade out?
fade-out-time: 1

#-------------------------------------------#
#           Lucky Crate Settings            #
#-------------------------------------------#

# Should lucky chests spawn when blocks are broken in creative mode?
luckychest-creative: false

# After how many MINUTES should a lucky crate despawn? Set to -1 for them to NEVER disappear.
# This is just to prevent lag from having so many lucky crates around the world.
# 1 hour = 60 minutes
# 1 day = 1440 minutes
# 1 month = 43800 minutes
luckychest-despawn-after: -1

# Should lucky chests spawn if the block was placed (and not naturally generated)?
#  NOTE: 'placed block' data is ERASED after restart (NOT RELOAD) so it is not server-resource intensive to store every
#  placed block. This is simply meant to be a deterrent from people placing and then re-breaking the blocks.
luckychest-allow-placed-blocks: false

#-----------------------------------------------#
#             Virtual Crate Settings            #
#-----------------------------------------------#

# What multicrate is run when /crates is run
crates-command-multicrate: AllCrates

# What is the name of the menu of the /crates inventory
crates-command-name: '&b&lVirtual &7&lCrates'

# If a player has both a virtual key and a physical key, should it prioritize the physical or virtual key?
prioritize-physical-key: true

# To open a crate in a MultiCrate, should a virtual key AND a virtual crate be required? An example
#   for something like: virtual crates are earned through minigames, virtual keys are bought on buycraft.
require-virtual-crate-and-key: false

# What do you want the inventory name of the /crates claim menu to be?
crates-claim-inventory-name: '&7&l> &6&lCrates Claim'

# Should people be allowed to deposit keys into the /crates claim menu?
crates-claim-allow-deposit: true

#-------------------------------------------------------#
#       Rewards Display Inventory + Display Items       #
#-------------------------------------------------------#

# Would you like the rewards display inventory to be enabled?
enabled: true

# Should the multicrate reward display inventory open on right or left click?
mc-reward-display-leftclick: true

# The format for the name and lore of the item(s) being displayed in the inventory
#   note: If a reward has a custom lore value set for it, this will be ignored.
#
# > %rewardname% - Name of the reward
# > %displayname% - Display name of the reward
# > %chance% - The actual calculated percent chance of winning that reward
# > %rarity% - Rarity of the item.
# > %writtenchance% - The chance that is written for that reward
inv-reward-item-name: '&c%displayname%'
inv-reward-item-lore:
  - '&7-'
  - '&eChance: &6%writtenchance%%'

#---------------------------------------------------------#
#       Deprecated Values (Should no longer be used)      #
#---------------------------------------------------------#
# NOTE: These values still work, but their alternatives are suggested.

# The format for the name of the inventory displaying the rewards.
# > %crate% - Name of the crate.
#
# !! REPLACED BY THE 'reward-display.name' VALUE IN EACH .CRATE FILE
inv-reward-display-name: '&4%crate% &cRewards'

# Should multicrates show the 'virtual-key-lore' value on crate items?
#
# !! REPLACED BY USING %keys% IN THE 'crate.lore' VALUE IN EACH .CRATE FILE
virtual-crate-keycount: false

# Should multicrates show the 'virtual-crate-lore' value on crate items?
#
# !! REPLACED BY USING %crates% IN THE 'crate.lore' VALUE IN EACH .CRATE FILE
virtual-crate-cratecount: false

# Format for how the player's virtual keys and crates are show
#    note: This is added to the bottom of the displayed crate's lores.
#
# > %keys% - Amount of virtual keys
# > %crates% - Amount of virtual crates
#
# !! REPLACED BY USING %keys% AND %crate% IN THE 'crate.lore' VALUE IN EACH .CRATE FILE
virtual-crate-lore: '&cCrates: &f(&7%crates%&f)'
virtual-key-lore: '&cKeys: &f(&7%keys%&f)'

# Should the crates automatically close when their animations is done playing?
#
# REPLACED BY
auto-close: true