# --------------------------------------------------------------
#
# Thanks for using MMOItems!
#
# --------------------------------------------------------------

# Notifies players with the 'mmoitems.update-notify' perm node when
# they join the server if a new update is available for download.
# Requires /reload when changed.
update-notify: true

# The plugin takes a few milliseconds to read the item data from the item
# config and a few hundred MICROseconds to actually generate it. Caching the
# item allows to skip the first step which reduces ~6 times the delay needed
# to generate any mmoitem.
#
# However, it does take up much more RAM space. Toggle it on if you have
# too many items which makes item generation time consuming. Toggle it off
# to get some spare memory.
use-item-caching: true

# Enable/disable the plugin iterating over the whole player inventory
# instead of just the players armor and held items.
# This option is required for the Ornamnet item type, however
# it CAN cause lag and/or take a lot of memory.
iterate-whole-inventory: false

# When this is set to true, skins can only be applied to an item ONCE. 
locked-skins: true

# Enable/Disable abilities in the players offhand, stops
# players using abilities when interacting with chests, mining etc.
# Very useful if your have a lot of items that your players use in their
# off-hand like tomes!
disable-abilities-in-offhand: true

# By default, all player inventories will be updated every
# 10 ticks which corresponds to 2 inventory updates a second.
inventory-update-delay: 1

# Changes the default value for some stats.
default:
    attack-speed: 0.67
    range: 16
    blunt-rating: 33
    recoil: 0.1

# Enable/disable the item glow feature. Make sure you
# reload your server when changing this option. This
# option might take extra performance so consider toggling
# it off if you have players or mobs dropping many items.
item-glow: true

item-upgrading:

    # Display name suffix for upgraded items.
    name-suffix: '&f &e(+#lvl#)'
    
    # Whether to display in Item Name or Lore
    # Disable if item renaming is available to players.
    # If set to 'false', remember to include
    # %upgrade_level% in your item lore.
    display-in-name: true

    # How stat changes are formatted
    # in the stat suffix.
    stat-change-suffix: '&f &e(+#stat#)'

    # Whether or not to display which
    # stats are changed in the lore.
    # EXPERIMENTAL FEATURE
    display-stat-changes: true

soulbound:
    # Edit soulbound damage when players try to use
    # items which are not bound to themselves.
    damage:
        base: 2
        per-lvl: 2
        
# Enable, disable and customize the weapon effects here.
# Weapon effects depend on the item type & type set.
item-ability:
    staff:
        enabled: true
        cooldown: 30
        power: 1
    gauntlet:
        enabled: true
        cooldown: 60
        power: 1
    blunt:
        aoe:
            enabled: true
            cooldown: 4
        stun:
            enabled: true
            chance: 5
            cooldown: 30
            power: 1
    slashing:
        enabled: true
        cooldown: 5
    piercing:
        enabled: true
        cooldown: 4

gem-sockets:
    # Define the text you need to enter in the
    # item gem sockets if you want to create an
    # uncolored gem socket i.e a socket for any type of gem.
    uncolored: 'Uncolored'

custom-blocks:
    # Whether or not custom blocks should
    # generate in the world according to
    # their generation template.
    enable-world-gen: false
    # Whether or not to remove mushroom block drops
    # from the droplist when mining a mushroom block
    # with silk-touch.
    # HIGHLY Recommended for servers that use
    # custom blocks, as the mushroom blocks can BREAK everything.
    replace-mushroom-drops: false

# Use this option if your chat management plugin is having
# conflicts with the MMOItems chat input feature. This will
# bring up an anvil GUI which you can input text in instead
# of using the chat.
anvil-text-input: false

# Players can't use their weapon/abilities when holding
# two-handed item and one other item simultaneously.
# When toggled off, players still receive slow 4.
two-handed-item-restriction: true

# You can select what char will be used to create
# the item ability cooldown progress bar.
cooldown-progress-bar-char: █

# When toggled off, players can't damage each other using item abilities.
ability-player-damage: false

# When enabled, all custom recipes will be in the recipe book on join.
# If toggled off they will have to use to recipe once to add it to their book.
auto-recipe-book: true

# Displays a message on the action bar instead of on the chat.
# Can be used to reduce chat spam.
# Might interfere with other action bar plugins.
action-bar-display:
    ability-cooldown: true
    item-cooldown: true
    not-enough-mana: true
    not-enough-stamina: true
    two-handed: true
    cant-use-item: true
    mitigation: true
    item-break: false

# Displays in-game damage indicators.
# Requires HolographicDisplays/Holograms to work.
# Requires /reload when enabled/disabled.
game-indicators:
    damage:
        enabled: true
        decimal-format: '0.#'
        format: '&e&l✦&c&l#'
    heal:
        enabled: true
        decimal-format: '0.#'
        format: '&c&l❤ &a&l#'

# Unregisters all crafting recipes. Requires /reload.
# Also disables the advanced workbench when disabling advanced craftings.
disable-craftings: false

# "repair" prevents players from repairing MMOItems.
# "smelt" prevents players from smelting MMOItems.
# 'enchant" disables enchanting for MMOItems.
# "craft" prevents players from using MMOItems as ingredients.
# "arrow-shooting" prevents players from shooting any MMOItem that is an arrow.
disable-interactions:
    interact: false
    repair: false
    enchant: false
    smelt: false
    craft: false
    arrow-shooting: false

# Block types that can't be broken by an ability/item effect
block-blacklist:
- OBSIDIAN
- BEDROCK

# Allows/disables the permissions needed in order to use items/abilities.
# General permission node for abilities: mmoitems.ability.ability-id
# Ex: - mmoitems.ability.fire-meteor
#     - mmoitems.ability.slow
#     - mmoitems.ability.cursed-fangs
#     etc.
permissions:
    abilities: false
    items: true

# Disables non MMOItems from being crafted in the vanilla workbench.
# Add [] if the list is empty.
disable-vanilla-recipes: []
# - DIAMOND_PICKAXE
# - IRON_BLOCK
