# -----------------------------------------------------
# Plan Bukkit Configuration file
# More information about each setting:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Bukkit-Configuration
# -----------------------------------------------------
Server:
    ServerName: Adventure
# -----------------------------------------------------
Plugin:
    Logging:
        # More information about Locale
        # https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Localization
        Locale: default
        Create_new_locale_file_on_next_enable: false
        Debug: false
        Dev: false
        Delete_logs_after_days: 2
    Update_notifications:
        # Display update notification on the website
        Check_for_updates: true
        Notify_about_DEV_releases: false
    Configuration:
        Allow_proxy_to_manage_settings: true
# -----------------------------------------------------
# Supported databases: SQLite, H2, MySQL
# -----------------------------------------------------
Database:
    Type: MySQL
    MySQL:
        Host: localhost
        Port: 3306
        User: minecraft
        Password: kWz7Y8eK0tMCUvr0Cm
        Database: minecraft_live
        # Launch options to append after mysql driver address
        Launch_options: ?rewriteBatchedStatements=true&useSSL=false
    H2:
        User: root
        Password: minecraft
# -----------------------------------------------------
# More information about SSL Certificate Settings:
# https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
# -----------------------------------------------------
Webserver:
    Port: 5001
    Alternative_IP: false
        # %port% is replaced automatically with Webserver.Port
        Address: AdventuresCraft.net:%port%
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 0.0.0.0
    Security:
        SSL_certificate:
            KeyStore_path: Cert.jks
            Key_pass: default
            Store_pass: default
            Alias: alias
        # HTTPS is required for Login.
        Disable_authentication: false
        # Cross-Origin Resource Sharing (Requests from non-Plan web pages)
        # https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
        CORS:
            Allow_origin: "*"
        IP_whitelist: true
            Whitelist:
              - "69.242.107.117"
    Disable_Webserver: true
    External_Webserver_address: https://AdventuresCraft.net
# -----------------------------------------------------
Data_gathering:
    Geolocations: true
    # Please accept the EULA to download GeoLite2 IP-Country Database
    # https://www.maxmind.com/en/geolite2/eula
    Accept_GeoLite2_EULA: true
    Ping: true
    Disk_space: true
    Commands:
        Log_unknown: true
        Log_aliases_as_main_command: true
# -----------------------------------------------------
# Supported time units: MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
# -----------------------------------------------------
Time:
    Delays:
        Ping_server_enable_delay: 300
            Unit: SECONDS
        Ping_player_join_delay: 30
            Unit: SECONDS
        Wait_for_DB_Transactions_on_disable: 20
            Unit: SECONDS
    Thresholds:
        # How long player needs to be idle until Plan considers them AFK
        AFK_threshold: 3
            Unit: MINUTES
        # Activity Index considers last 3 weeks and uses these thresholds in the calculation
        # The index is a number from 0 to 5.
        # These numbers were calibrated with data of 250 players (Small sample size).
        Activity_index:
            Playtime_threshold: 30
                Unit: MINUTES
        Remove_inactive_player_data_after: 180
            Unit: DAYS
        # Includes players online, tps and performance time series
        Remove_time_series_data_after: 90
            Unit: DAYS
        Remove_ping_data_after: 14
            Unit: DAYS
        Remove_disabled_extension_data_after: 2
            Unit: DAYS
    Periodic_tasks:
        Extension_data_refresh_every: 1
            Unit: HOURS
        Check_DB_for_server_config_files_every: 1
            Unit: MINUTES
        Clean_Database_every: 1
            Unit: HOURS
# -----------------------------------------------------
Display_options:
    # More information about Themes:
    # https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Themes
    Theme: default
    Sessions:
        Show_on_page: 50
        # By Default World playtime pie is ordered alphabetically.
        # Colors will be determined alphabetically in any case.
        Order_world_pies_by_percentage: false
    Players_table:
        Show_on_server_page: 2500
        Show_on_players_page: 25000
    Open_player_links_in_new_tab: false
    Graphs:
        Show_gaps_in_data: false
        TPS:
            High_threshold: 18
            Medium_threshold: 10
        Disk_space:
            High_threshold: 500
            Medium_threshold: 100
    Command_colors:
        Main: '&2'
        Secondary: '&7'
        Highlight: '&f'
# -----------------------------------------------------
Formatting:
    Decimal_points: '#.##'
    Time_amount:
        Year: '1 year, '
        Years: '%years% years, '
        Month: '1 month, '
        Months: '%months% months, '
        Day: '1d '
        Days: '%days%d '
        Hours: '%hours%h '
        Minutes: '%minutes%m '
        Seconds: %seconds%s
        Zero: 0s
    # Dates settings use Java SimpleDateFormat.
    # You can find the patterns & examples here:
    # https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
    Dates:
        # Show_recent_day_names replaces day number with Today, Yesterday, Wednesday etc.
        Show_recent_day_names: true
            # Non-regex pattern to replace
            DatePattern: 'MMM d YYYY'
        Full: 'MMM d YYYY, HH:mm:ss'
        NoSeconds: 'MMM d YYYY, HH:mm'
        JustClock: HH:mm:ss
        # TimeZone Option uses format 'GMT+2' or 'GMT-04:30'
        # Other valid options are 'server' and 'UTC'
        TimeZone: 'EST'
# -----------------------------------------------------
# World aliases can be used to rename worlds and to combine multiple worlds into a group.
# -----------------------------------------------------
World_aliases:
    Spawn: Spawn
    Homes: Homes
    world: world
    Aberration: Aberration
    Prison: Prison
# -----------------------------------------------------
# These settings will make Plan write .js, .css, .json and .html files to some location on disk.
# Relative path will render to /plugins/Plan/path
# Make sure user running the server has write permissions to the path.
# On networks export is disabled on Bukkit/Sponge servers.
# -----------------------------------------------------
Export:
    HTML_Export_path: 'Analysis Results'
    JSON_Export_path: 'Raw JSON'
    Parts:
        # Player pages/JSON are only written on join/leave.
        Player_pages: false
        Player_JSON: false
        Players_page: false
        Server_page: false
        Server_JSON: false
    # All player pages/JSON can be exported by using /plan m export players
    Export_player_on_login_and_logout: false
    # If there are multiple servers the period is divided evenly to avoid export of all servers at once
    # Also affects Players page export
    Server_refresh_period: 20
        Unit: MINUTES
# -----------------------------------------------------
# These settings affect Plugin data integration.
# If a plugin is causing issues the integration can be disabled by setting Plugin_name.Enabled: false
# -----------------------------------------------------
Plugins:
    BSkyBlock:
        Enabled: true
    Buycraft:
        # http://help.buycraft.net/article/36-where-to-find-the-secret-key
        Secret: 'TxzmtI6SSMoi7LvqEH3pn2J5zzwPoaYU'
        Enabled: true
    DiscordSRV:
        Enabled: true
    Economy (Vault):
        Enabled: true
    Essentials:
        Enabled: false
    Factions:
        HideFactions:
          - ExampleFaction
    LuckPerms:
        Enabled: true
    Permission Groups (Vault):
        Enabled: true
    Towny:
        HideTowns:
          - ExampleTown
    ViaVersion:
        Enabled: true
    nuVotifier:
        Enabled: true
# The files are placed in /Plan/web/ if the setting is 'true' when accessed.
Customized_files:
    Plan:
        css/noauth,css: false
        css/sb-admin-2,css: false
        css/style,css: false
        favicon,ico: false
        img/Flaticon_circle,png: false
        js/color-selector,js: false
        js/graphs,js: false
        js/pingTable,js: false
        js/player-values,js: false
        js/sb-admin-2,js: false
        js/server-values,js: false
        js/sessionAccordion,js: false
        js/xmlhttprequests,js: false
        player,html: false
        server,html: false
        vendor/bootstrap/js/bootstrap,bundle,min,js: false
        vendor/datatables/dataTables,bootstrap4,min,js: false
        vendor/datatables/jquery,dataTables,min,js: false
        vendor/fontawesome-free/css/all,min,css: false
        vendor/fontawesome-free/webfonts/fa-brands-400,woff2: false
        vendor/fontawesome-free/webfonts/fa-regular-400,woff2: false
        vendor/fontawesome-free/webfonts/fa-solid-900,woff2: false
        vendor/fullcalendar/fullcalendar,min,css: false
        vendor/fullcalendar/fullcalendar,min,js: false
        vendor/highcharts/drilldown,js: false
        vendor/highcharts/highcharts-more,js: false
        vendor/highcharts/highstock,js: false
        vendor/highcharts/map,js: false
        vendor/highcharts/no-data-to-display,js: false
        vendor/highcharts/world,js: false
        vendor/jquery/jquery,min,js: false
        vendor/momentjs/moment,js: false
