# PlaceholderAPI
# Version: 2.10.9
# Created by: extended_clip
# Contributors: https://github.com/PlaceholderAPI/PlaceholderAPI/graphs/contributors
# Issues: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
# Expansions: https://api.extendedclip.com/all/
# Wiki: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
# Discord: https://helpch.at/discord
# No placeholders are provided with this plugin by default.
# Download placeholders: /papi ecloud
check_updates: true
cloud_enabled: true
cloud_allow_unverified_expansions: false
boolean:
  'true': 'yes'
  'false': 'no'
date_format: MM/dd/yy HH:mm:ss
expansions:
  vault:
    baltop:
      check_delay: 30
      cache_size: 100
      enabled: true
    formatting:
      thousands: k
      trillions: T
      quadrillions: Q
      billions: B
      millions: M
  player:
    ping_color:
      medium: '&e'
      high: '&a'
      low: '&c'
  server:
    tps_color:
      high: '&a'
      low: '&c'
      medium: '&e'
    server_name: A Minecraft Server
  localtime:
    date_format: dd/MM/yyyy hh:mma
  math:
    Precision: 3
    Rounding: half_up
    Debug: false
