# Welcome to SkBee

settings:
  # Enable this if you would like to see more verbose debug messages
  debug: false

# Disable elements you do not plan to use.
elements:
  # Enable NBT elements
  nbt: true

  # Enable Scoreboard elements
  scoreboard: true

  # Enable custom recipe elements
  # Note: Only available on 1.13+
  recipe: true

  # Enable bound elements
  # Bounds are like custom world guard regions
  bound: true

  # Enable structure elements
  # Note: Only available on 1.9.4+
  structure: true

  # Enable VirtualFurnace elements
  # Note: Only available on 1.13+
  # This feature is semi-experimental, please use with caution
  virtual-furnace: false

  # Enable Text Component elements
  text-component: true

  # Enable pathfinding elements
  # Note: Only available on Paper 1.13+
  pathfinding: true

  # Enable world creator elements
  world-creator: false
  # Whether or not custom worlds should automatically load on server start
  # If disabled, you will need to load worlds with the load world effect
  auto-load-custom-worlds: true

recipe:
  # This is the namespace all recipes will be saved under, you can choose whatever you wish
  # Example, when using the minecraft recipe command `/minecraft:recipe give playerName skrecipe:my_custom_recipe
  # If upgrading to this plugin from SkRecipe, keep this namespace as `skrecipe` to ensure previous recipes
  # loaded to players will continue to work
  namespace: "skrecipe"
