# 
# MythicMobsExtension Config
# Informations available at github.com/BerndiVader/MythicMobsExtension/wiki/Config
Configuration:
  Version: 2
  Debug: false
  Update_Notification: true
  Patches:
    NaN_Patch: true
  Modules:
    Mythic_Players: true
    Mythic_Thiefs: true
    Cached_Owners: true
  Entities:
    Mythic_Parrot: true
  Compatibility:
    Worldguard: true
    Factions: true
    RPGItems: true
    MobArena: true
    Holographic_Displays: true
  Externals: true
  Javascript: true
  Quests: true
  NPC: true
  PRE44SPAWN: false
  Metadata:
    Delay: 480
